# Generated by Django 4.2.5 on 2023-09-27 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=25)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('brewery', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=25)),
                ('style', models.CharField(max_length=25)),
                ('isapproved', models.BooleanField(default=False)),
            ],
        ),
    ]
