# Generated by Django 4.2.5 on 2023-11-28 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webpage', '0002_rename_date_beer_published_date_beer_alcohol_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='rating',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.beer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
