# Generated by Django 4.2.5 on 2023-11-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_remove_beer_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='type',
        ),
    ]
