# Generated by Django 4.2.5 on 2023-11-29 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_alter_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='review',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
