# Generated by Django 4.2.5 on 2023-12-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_rename_user_review_author_review_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='picture',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
