# Generated by Django 4.2.5 on 2023-12-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0010_mybeer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybeer',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mybeer',
            name='additives',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mybeer',
            name='hops',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mybeer',
            name='malts',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
