# Generated by Django 4.2.5 on 2023-12-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0016_review_fruit_review_hop_review_malt_review_roast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='email@gmail.com', max_length=50),
        ),
    ]
